name: Build and Publish to TestPyPI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: 🧠 Extract version from pyproject.toml
        id: version
        run: |
          version=$(grep '^version *= *' pyproject.toml | sed -E 's/version *= *"([^"]+)"/\1/')
          echo "📦 Extracted version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distribution
        run: |
          rm -rf dist/
          python -m build

      - name: 🚀 Upload to TestPyPI
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

      - name: 📦 Retry install from TestPyPI until expected version
        run: |
          set -e

          EXPECTED_VERSION="${{ steps.version.outputs.version }}"
          echo "🧠 Expecting to install version: $EXPECTED_VERSION"

          for i in {1..5}; do
            echo "🔁 Attempt $i to install path-manager-qiaoy..."
            pip uninstall -y path-manager-qiaoy || true
            pip install --no-cache-dir -i https://test.pypi.org/simple/ path-manager-qiaoy

            INSTALLED_VERSION=$(pip show path-manager-qiaoy | grep ^Version: | cut -d' ' -f2)
            echo "📦 Installed version: $INSTALLED_VERSION"

            if [[ "$INSTALLED_VERSION" == "$EXPECTED_VERSION" ]]; then
              echo "✅ Version match! Installed: $INSTALLED_VERSION"
              break
            fi

            echo "⏳ Version mismatch. Expecting $EXPECTED_VERSION but got $INSTALLED_VERSION"
            echo "⏱️ Waiting 15 seconds before retry..."
            sleep 15
          done

          # Final check
          FINAL_VERSION=$(pip show path-manager-qiaoy | grep ^Version: | cut -d' ' -f2)
          if [[ "$FINAL_VERSION" != "$EXPECTED_VERSION" ]]; then
            echo "❌ Still not the expected version after 5 attempts!"
            exit 1
          fi

      - name: ✅ Test CLI proj init
        run: |
          proj init my_test_proj
          test -f my_test_proj/work/start.py
          grep -q 'print("Project initialized successfully!")' my_test_proj/work/start.py